type TestData = {
  name: string;
  preferredPronouns: string;
  email: string;
  phoneNumber: string;
  description: string;
  size: string;
  placement: string;
  color: "Black & Grey" | "Colored";
};

export const data: TestData[] = [
  {
    name: "Chico Bean",
    preferredPronouns: "The Man",
    email: "chico@bean.com",
    phoneNumber: "4569874561",
    description: "Small baby chico bean",
    size: "practically invisible",
    placement: "need to know",
    color: "Black & Grey",
  },
  {
    name: "James Bond",
    preferredPronouns: "Mr/Sir",
    email: "james@bond.com",
    phoneNumber: "700-007-0700",
    description: "Golden Eye",
    size: "2-3 inches",
    placement: "I can only tell my artist",
    color: "Colored",
  },
  {
    name: "Ferris Bueller",
    preferredPronouns: "he/him",
    email: "ferris@bueller.com",
    phoneNumber: "9987895521",
    description: "1961 Ferrari 250 GT California Spyder",
    size: "4-6 inches",
    placement: "calf",
    color: "Colored",
  },
  {
    name: "Martin Blank",
    preferredPronouns: "he/him",
    email: "martin@blank.com",
    phoneNumber: "8889991122",
    description: "John Cusack holding a boombox",
    size: "Whatever size is the best",
    placement: "rib cage",
    color: "Colored",
  },
  {
    name: "Samewise Gamgee",
    preferredPronouns: "they/them",
    email: "samewise@gamgee.com",
    phoneNumber: "7207732143",
    description: "A portrait of my idol!",
    size: "6-8 inches",
    placement: "Shoulder",
    color: "Black & Grey",
  },
  {
    name: "Ethan Hunt",
    preferredPronouns: "he/him",
    email: "ethan@hunt.com",
    phoneNumber: "8089091233",
    description: "Some sort of ghost protocol metaphor",
    size: "Small on my leg",
    placement: "leg",
    color: "Black & Grey",
  },
  {
    name: "Edna Mode",
    preferredPronouns: "she/her",
    email: "edna@mode.com",
    phoneNumber: "3216547891",
    description: "No capes! Branded across my chest",
    size: "Large as fuck =)",
    placement: "chest",
    color: "Black & Grey",
  },
  {
    name: "Billy Bob Thornton",
    preferredPronouns: "he/him",
    email: "nobodynoes@gmail.com",
    phoneNumber: "2038675309",
    description: "My favorite character, Bad Santa!",
    size: "8 inches",
    placement: "on arm",
    color: "Colored",
  },
  {
    name: "Ash Williams",
    preferredPronouns: "he/him",
    email: "ash@willims.com",
    phoneNumber: "9871326541",
    description: "A chainsaw on my good hand",
    size: "3-4 inches",
    placement: "back of my hand",
    color: "Black & Grey",
  },
  {
    name: "Marty McFly",
    preferredPronouns: "he/him",
    email: "marty@mcfly.com",
    phoneNumber: "1231478523",
    description: "Flux Capacitor",
    size: "4-6 inches",
    placement: "calf",
    color: "Colored",
  },
  {
    name: "John McClane",
    preferredPronouns: "he/him",
    email: "john@mcClane.com",
    phoneNumber: "7983692851",
    description: "Christmas Tree",
    size: "3-5",
    placement: "forearm",
    color: "Colored",
  },
  {
    name: "King Schultz",
    preferredPronouns: "he/him",
    email: "king@schultz.com",
    phoneNumber: "78914447853",
    description: "a recreation of my most famous bounty",
    size: "a foot",
    placement: "back/shouler",
    color: "Black & Grey",
  },
  {
    name: "Ellen Ripley",
    preferredPronouns: "she/her",
    email: "ellen@ripley.com",
    phoneNumber: "9633699633",
    description: `"get away from her you BITCH!"`,
    size: "8 cm",
    placement: "dealer's choice",
    color: "Black & Grey",
  },
  {
    name: "Sarah Connor",
    preferredPronouns: "she/her",
    email: "sarah@connor.com",
    phoneNumber: "2582588522",
    description: "my son's name",
    size: "4 inches",
    placement: "shoulder",
    color: "Black & Grey",
  },
  {
    name: "Wednesday Addams",
    preferredPronouns: "she/her",
    email: "wednesday@addams.com",
    phoneNumber: "1471471474",
    description: "Small 'W'",
    size: "1 inch",
    placement: "Behind my ear",
    color: "Black & Grey",
  },
  {
    name: "Inigo Montoya",
    preferredPronouns: "they/them",
    email: "inigo@montoya.com",
    phoneNumber: "4566544564",
    description: "A portrait of my father",
    size: "8 mm",
    placement: "shoulder/arm",
    color: "Colored",
  },
  {
    name: "Han Solo",
    preferredPronouns: "he/him",
    email: "han@solo.com",
    phoneNumber: "7899877899",
    description: "Picture of the Millennium Falcon ",
    size: "a foot",
    placement: "back",
    color: "Black & Grey",
  },
  {
    name: "Vito Corleone",
    preferredPronouns: "he/him",
    email: "vito@corleone.com",
    phoneNumber: "7894651234",
    description: "guns on my back with cross and rosary",
    size: "bigger than a foot",
    placement: "back",
    color: "Black & Grey",
  },
  {
    name: "Axel Foley",
    preferredPronouns: "he/him",
    email: "axel@foley.com",
    phoneNumber: "4564564564",
    description: "Something related to something",
    size: "10",
    placement: "chest",
    color: "Black & Grey",
  },
  {
    name: "Ron Burgundy",
    preferredPronouns: "he/him",
    email: "ron@burgundy.com",
    phoneNumber: "7897897897",
    description: `I want the words "Stay Classy" as a tramp stamp`,
    size: "8",
    placement: "lower back",
    color: "Colored",
  },
];

/*
  {
    name: "",
    preferredPronouns: "",
    email: "",
    phoneNumber: "",
    description: "",
    size: "",
    placement: "",
    color: "",
  },
*/
